// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID               uuid.UUID
	Username         string
	Email            string
	PasswordVerifier string
	EncryptionSalt   string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
