// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID                      uuid.UUID
	Email                   string
	Username                string
	Salt                    []byte
	AuthVerifier            []byte
	IdentityPublicKey       []byte
	EncIdentityPrivateKey   []byte
	IdentityPrivateKeyNonce []byte
	VaultPublicKey          []byte
	EncVaultPrivateKey      []byte
	VaultPrivateKeyNonce    []byte
	CreatedAt               time.Time
	UpdatedAt               time.Time
}
