// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID
	Email         string
	Username      string
	Salt          []byte
	AuthVerifier  []byte
	PublicKey     []byte
	EncPrivateKey []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
