// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_verifier, encryption_salt)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_verifier, encryption_salt, created_at, updated_at
`

type CreateUserParams struct {
	Username         string
	Email            string
	PasswordVerifier string
	EncryptionSalt   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordVerifier,
		arg.EncryptionSalt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordVerifier,
		&i.EncryptionSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_verifier, encryption_salt, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordVerifier,
		&i.EncryptionSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
