// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    username,

    salt,
    auth_verifier,

    identity_public_key,
    enc_identity_private_key,
    identity_private_key_nonce,

    vault_public_key,
    enc_vault_private_key,
    vault_private_key_nonce
) VALUES (
    $1, $2, $3, $4, 
    $5, $6, $7, 
    $8, $9, $10
)
RETURNING id, email, username, salt, auth_verifier, identity_public_key, enc_identity_private_key, identity_private_key_nonce, vault_public_key, enc_vault_private_key, vault_private_key_nonce, created_at, updated_at
`

type CreateUserParams struct {
	Email                   string
	Username                string
	Salt                    []byte
	AuthVerifier            []byte
	IdentityPublicKey       []byte
	EncIdentityPrivateKey   []byte
	IdentityPrivateKeyNonce []byte
	VaultPublicKey          []byte
	EncVaultPrivateKey      []byte
	VaultPrivateKeyNonce    []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Salt,
		arg.AuthVerifier,
		arg.IdentityPublicKey,
		arg.EncIdentityPrivateKey,
		arg.IdentityPrivateKeyNonce,
		arg.VaultPublicKey,
		arg.EncVaultPrivateKey,
		arg.VaultPrivateKeyNonce,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Salt,
		&i.AuthVerifier,
		&i.IdentityPublicKey,
		&i.EncIdentityPrivateKey,
		&i.IdentityPrivateKeyNonce,
		&i.VaultPublicKey,
		&i.EncVaultPrivateKey,
		&i.VaultPrivateKeyNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSaltByEmail = `-- name: GetSaltByEmail :one
SELECT salt FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetSaltByEmail(ctx context.Context, email string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSaltByEmail, email)
	var salt []byte
	err := row.Scan(&salt)
	return salt, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, salt, auth_verifier, identity_public_key, enc_identity_private_key, identity_private_key_nonce, vault_public_key, enc_vault_private_key, vault_private_key_nonce, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Salt,
		&i.AuthVerifier,
		&i.IdentityPublicKey,
		&i.EncIdentityPrivateKey,
		&i.IdentityPrivateKeyNonce,
		&i.VaultPublicKey,
		&i.EncVaultPrivateKey,
		&i.VaultPrivateKeyNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, username, salt, auth_verifier, identity_public_key, enc_identity_private_key, identity_private_key_nonce, vault_public_key, enc_vault_private_key, vault_private_key_nonce, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Salt,
		&i.AuthVerifier,
		&i.IdentityPublicKey,
		&i.EncIdentityPrivateKey,
		&i.IdentityPrivateKeyNonce,
		&i.VaultPublicKey,
		&i.EncVaultPrivateKey,
		&i.VaultPrivateKeyNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
